Setup unit testing (#2)
* Setup unit testing

* Add more tests

* Add step for validating ROBLOSECURITY

* Fix

* Use bash for validating the token

* Try with `-z`

* Use bash shell explicitly

* Fix condition

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,3 +28,42 @@ jobs:
 
       - name: Format
         run: stylua --check src/
+
+  tests:
+    runs-on: windows-latest
+    timeout-minutes: 10
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Check for ROBLOSECURITY secret
+        shell: bash
+        run: |
+          if [[ -z "$ROBLOSECURITY" ]]; then
+              echo "Could not find ROBLOSECURITY token. Add a secret named 'ROBLOSECURITY' to the repo and try again"
+              exit 1
+          else
+              echo "Found ROBLOSECURITY token. Continuing..."
+          fi
+        env:
+          ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
+
+      - name: Install toolchain
+        uses: Roblox/setup-foreman@v1
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Install dependencies
+        run: wally install
+
+      - name: Build place file
+        run: rojo build dev.project.json -o studio-tests.rbxlx
+
+      - name: Install Roblox Studio
+        uses: OrbitalOwen/roblox-win-installer-action@1.1
+        with:
+          cookie: ${{ secrets.ROBLOSECURITY }}
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Run tests
+        run: run-in-roblox --place studio-tests.rbxlx --script tests/init.server.lua
